### ISSUE TITLE
Wiki - Specify Author

### ISSUE THREAD

**Issue by JonathanJustavino** [dbpedia/gstore#37]
It should be possible to set an author when saving a document.
The provided author should appear as the author in the git history.

**Comment by manonthegithub** [comment]
IN git you usually specify Name and Email, what kinda data you want to specify for Author? I suppose at least email... do you want to specify a name too?

**Comment by JonathanJustavino** [comment]
For now an arbitrary string suffices, passed via query parameter "author".
E.g. --author="John Doe <>"

**Comment by manonthegithub** [comment]
Okay then what should I put as email? As long as I remember Git requires both, so I have to specify anyways both

**Comment by manonthegithub** [comment]
@JonathanJustavino now it is like that: `.setCommitter("databus", "databus@infai.org")`

if we put only name, what should I put for email (I can try to put name, not sure if git will allow that, generally email is necessary)?
if we put email, I can just duplicate it for name, here no problem
other options?

**Comment by JonathanJustavino** [comment]
The requirement is to leave the email empty, e.g. ?author="databus"&email="<>" or --user "John Doe < >", if that is possible.

**Comment by holycrab13** [comment]
To avoid confusion:

what we want:
* store an author name, potentially also an email with a commit so it shows up in the history

why do we want it:
* we want to use the gstore as a backbone for a more wiki-like approach when working with graphs. 
* It should at a later stage be possible to get the git history as RDF and also to revert changes in order to track who did what.

Git requires a username and email, but when doing ```git commit --user "John Doe <>"``` it leaves the email empty, so I assume this is also possible in the scala API. 

You could go with two query parameters ?author and ?email and set whatever is there. Should any of that fail, you could fall back to a default when not specified.

**Comment by manonthegithub** [comment]
Okay, looks clear now. l will check it out

**Comment by manonthegithub** [comment]
@holycrab13 @JonathanJustavino this should work now, please check

**Comment by manonthegithub** [comment]
@holycrab13 @JonathanJustavino `dev` branch!

**Comment by holycrab13** [comment]
Thank you, will have a look!
